### ISSUE TITLE
关于运行环境问题

### ISSUE THREAD

**Issue by tianfuchao** [zhaoyang21cn/SuiXinBoPHPServer#3]
后台服务程序必须是linux 么？windows 2012 是否支持

**Comment by alderzhang** [comment]
windows环境必须将相应的sig生成工具（tls_licence_tools）替换成windows版本，详见：
https://www.qcloud.com/document/product/269/1510
同时跨房连麦功能的linkSig生成工具目前只有linux版本，在windows下需要自行实现音视频权限的协议加密，详见：
https://www.qcloud.com/document/product/268/3220
